export default [
{
    id: 1,
    name: 'Meme Generator',
    imgUrl: 'meme-generator.png',
    description: 'A meme generator built with React, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/Meme-Generator',
    livePage: 'https://meme-generator-phi-fawn.vercel.app/',
},
{
    id: 2,
    name: 'Thanksgiving Menu',
    imgUrl: 'thanksgiving.png',
    description: 'A Thanksgiving menu page built with HTML5, vanilla JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/Thanksgiving-menu',
    livePage: 'https://christophercoding-a11y.github.io/Thanksgiving-menu/',
},
{
    id: 3,
    name: 'Detroix',
    imgUrl: 'detroix.png',
    description: 'A Detroit-themed page built with HTML5, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/detroixboostsrap',
    livePage: 'https://christophercoding-a11y.github.io/detroixboostsrap/',
},
{
    id: 4,
    name: 'Movie App',
    imgUrl: 'movie-app.png',
    description: 'A movie app built with React, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/movie-app',
    livePage: 'https://movie-app-sandy-three.vercel.app/',
},
{
    id: 5,
    name: 'Library App',
    imgUrl: 'library_app.png',
    description: 'A full-stack library app built with MySQL, Express, React, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/final_project',
    livePage: '#',
},
{
    id: 6,
    name: 'Restaurant Page',
    imgUrl: 'restaurant.png',
    description: 'A restaurant website built with HTML5, vanilla JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/restaurant',
    livePage: 'https://christophercoding-a11y.github.io/restaurant/',
},
{
    id: 7,
    name: 'Bloom',
    imgUrl: 'bloom.png',
    description: 'A themed menu page built with HTML5, vanilla JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/bloombs',
    livePage: 'https://christophercoding-a11y.github.io/bloombs/',
},
{
    id: 8,
    name: 'Dice Game',
    imgUrl: 'dicegame.png',
    description: 'A dice game built with HTML5, vanilla JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/Dicegame',
    livePage: 'https://christophercoding-a11y.github.io/Dicegame/',
},
{
    id: 9,
    name: 'Box Game',
    imgUrl: 'boxgame.png',
    description: 'A simple box game created with HTML5, vanilla JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/BoxGame',
    livePage: 'https://christophercoding-a11y.github.io/BoxGame/',
},
{
    id: 10,
    name: 'Snake Game',
    imgUrl: 'snakegame.png',
    description: 'A classic snake game made with HTML5, vanilla JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/snakegame',
    livePage: 'https://christophercoding-a11y.github.io/snakegame/',
},
{
    id: 11,
    name: 'To-Do List',
    imgUrl: 'todo.png',
    description: 'A simple to-do list application made with HTML5, vanilla JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/To-Do-List',
    livePage: 'https://christophercoding-a11y.github.io/To-Do-List/',
},
{
    id: 12,
    name: 'Regex Password Validator',
    imgUrl: 'regex.png',
    description: 'A password strength validator using regex, built with HTML5, vanilla JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/Regex',
    livePage: 'https://christophercoding-a11y.github.io/Regex/',
},
];