export default [
{
    id: 1,
    name: 'Meme Generator',
    imgUrl: 'meme-generator.png',
    description: 'An interactive meme generator built with React that allows users to create and share custom memes in real-time.',
    sourceCode: 'https://github.com/christophercoding-a11y/Meme-Generator',
    livePage: 'https://meme-generator-phi-fawn.vercel.app/',
},
{
    id: 2,
    name: 'Thanksgiving Menu',
    imgUrl: 'thanksgiving.png',
    description: 'Responsive Thanksgiving menu built with HTML, JavaScript, CSS and Bootstrap',
    sourceCode: 'https://github.com/christophercoding-a11y/Thanksgiving-menu',
    livePage: 'https://christophercoding-a11y.github.io/Thanksgiving-menu/',
},
{
    id: 3,
    name: 'Detroix',
    imgUrl: 'detroix.png',
    description: 'Detroit-themed site showcasing local culture using HTML, CSS and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/detroixboostsrap',
    livePage: 'https://christophercoding-a11y.github.io/detroixboostsrap/',
},
{
    id: 4,
    name: 'Movie App',
    imgUrl: 'movie-app.png',
    description: 'A movie-themed React app with a clean layout and styled components.',
    sourceCode: 'https://github.com/christophercoding-a11y/movie-app',
    livePage: 'https://movie-app-sandy-three.vercel.app/',
},
{
    id: 5,
    name: 'Library App',
    imgUrl: 'library_app.png',
    description: 'Full-stack library system with React, CSS, Bootstrap, Express, and MySQL',
    sourceCode: 'https://github.com/christophercoding-a11y/final_project',
    livePage: '#',
},
{
    id: 6,
    name: 'Restaurant Page',
    imgUrl: 'restaurant.png',
    description: 'Responsive restaurant site built with HTML, JavaScript and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/restaurant',
    livePage: 'https://christophercoding-a11y.github.io/restaurant/',
},
{
    id: 7,
    name: 'Bloom',
    imgUrl: 'bloom.png',
    description: 'A themed menu page built with HTML, JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/bloombs',
    livePage: 'https://christophercoding-a11y.github.io/bloombs/',
},
{
    id: 8,
    name: 'Dice Game',
    imgUrl: 'dicegame.png',
    description: 'Classic dice game made with HTML, JavaScript and Bootstrap',
    sourceCode: 'https://github.com/christophercoding-a11y/Dicegame',
    livePage: 'https://christophercoding-a11y.github.io/Dicegame/',
},
{
    id: 9,
    name: 'Box Game',
    imgUrl: 'boxgame.png',
    description: 'Simple box game built with HTML, JavaScript and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/BoxGame',
    livePage: 'https://christophercoding-a11y.github.io/BoxGame/',
},
{
    id: 10,
    name: 'Snake Game',
    imgUrl: 'snakegame.png',
    description: 'Classic snake game recreated with HTML, JavaScript and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/snakegame',
    livePage: 'https://christophercoding-a11y.github.io/snakegame/',
},
{
    id: 11,
    name: 'To-Do List',
    imgUrl: 'todo.png',
    description: 'Simple to-do list app built with HTML, JavaScript and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/To-Do-List',
    livePage: 'https://christophercoding-a11y.github.io/To-Do-List/',
},
{
    id: 12,
    name: 'Regex Password Validator',
    imgUrl: 'regex.png',
    description: 'Password strength validator using regex, built with HTML, JavaScript, CSS, and Bootstrap.',
    sourceCode: 'https://github.com/christophercoding-a11y/Regex',
    livePage: 'https://christophercoding-a11y.github.io/Regex/',
},
{
    id: 13,
    name: 'riddle game',
    imgUrl: 'riddle.png',
    description: 'A fun riddle quiz game built with HTML, CSS, and JavaScript.',
    sourceCode: 'https://github.com/christophercoding-a11y/riddlegame',
    livePage: 'https://christophercoding-a11y.github.io/riddlegame/',
},
];